name: kartazia
description: "A gamified digital gift card app for kids."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter

  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Backend
  supabase_flutter: ^2.6.0
  
  # Navigation & Deep Linking
  go_router: ^14.2.1

  url_launcher: ^6.3.0
  share_plus: ^10.0.0

  
  # UI & Utilities
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  shared_preferences: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
